"""Deterministic OpenAI-compatible E2E provider for the Compose test network."""

from __future__ import annotations

import json
import re
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any


def _analysis_reply(prompt: str) -> str:
    match = re.search(r'Datasources:\n(\[.*?\])\nOperations:', prompt, flags=re.DOTALL)
    if match is None:
        return json.dumps({'tabs': [], 'explanation': 'fixture'})
    try:
        datasources = json.loads(match.group(1))
    except json.JSONDecodeError:
        return json.dumps({'tabs': [], 'explanation': 'fixture'})
    if not datasources:
        return json.dumps({'tabs': [], 'explanation': 'fixture'})
    return json.dumps(
        {
            'tabs': [{'name': 'Fixture source', 'datasource_id': datasources[0]['id'], 'steps': []}],
            'explanation': 'Generated by deterministic E2E provider',
        },
    )


class OpenAIFixtureHandler(BaseHTTPRequestHandler):
    protocol_version = 'HTTP/1.1'

    def do_GET(self) -> None:
        if self.path == '/health':
            self._json(200, {'status': 'ok'})
            return
        if self.path == '/v1/models':
            self._json(200, {'data': [{'id': 'e2e-fixture-model', 'object': 'model', 'owned_by': 'data-forge-e2e'}]})
            return
        self._json(404, {'error': {'message': 'not found'}})

    def do_POST(self) -> None:
        if self.path != '/v1/chat/completions':
            self._json(404, {'error': {'message': 'not found'}})
            return
        size = int(self.headers.get('Content-Length', '0'))
        payload = json.loads(self.rfile.read(size))
        messages = payload.get('messages', [])
        prompt = '\n'.join(str(message.get('content') or '') for message in messages)
        latest = next(
            (str(message.get('content') or '') for message in reversed(messages) if message.get('role') == 'user'),
            '',
        )
        if '[e2e-delay]' in latest:
            time.sleep(8)
        if '[e2e-heartbeat]' in latest:
            time.sleep(18)
        content = _analysis_reply(prompt) if 'Generate a JSON object for a new analysis pipeline.' in prompt else f'E2E fixture reply: {latest}'
        self._json(
            200,
            {
                'id': 'chatcmpl-e2e-fixture',
                'object': 'chat.completion',
                'created': 1,
                'model': payload.get('model', 'e2e-fixture-model'),
                'choices': [
                    {
                        'index': 0,
                        'message': {'role': 'assistant', 'content': content},
                        'finish_reason': 'stop',
                    },
                ],
                'usage': {'prompt_tokens': 1, 'completion_tokens': 1, 'total_tokens': 2},
            },
        )

    def _json(self, status: int, value: dict[str, Any]) -> None:
        body = json.dumps(value, separators=(',', ':')).encode()
        self.send_response(status)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, _format: str, *_args: object) -> None:
        return


if __name__ == '__main__':
    ThreadingHTTPServer(('0.0.0.0', 8001), OpenAIFixtureHandler).serve_forever()
