// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,json_types=true"
// @generated from file dataforge_protocol/common.proto (package dataforge.runtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../buf/validate/validate_pb";
import type { ComputeRequestKind, ComputeRequestKindJson } from "./enums_pb";
import { file_dataforge_protocol_enums } from "./enums_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dataforge_protocol/common.proto.
 */
export const file_dataforge_protocol_common: GenFile = /*@__PURE__*/
  fileDesc("Ch9kYXRhZm9yZ2VfcHJvdG9jb2wvY29tbW9uLnByb3RvEhFkYXRhZm9yZ2UucnVudGltZSIhCgxFbXB0eVJlcXVlc3QSEQoJbmFtZXNwYWNlGAEgASgJItQBChRSdW50aW1lV29ya2VyUmVxdWVzdBIaCgl3b3JrZXJfaWQYASABKAlCB7pIBHICEAESGAoQcHJvdG9jb2xfdmVyc2lvbhgCIAEoBRJMCh1hbGxvd2VkX2NvbXB1dGVfcmVxdWVzdF9raW5kcxgDIAMoDjIlLmRhdGFmb3JnZS5ydW50aW1lLkNvbXB1dGVSZXF1ZXN0S2luZBIYChB0YXJnZXRfbmFtZXNwYWNlGAUgASgJSgQIBBAFUhhjb21wdXRlX25hbWVzcGFjZV9vZmZzZXQiMwoVUnVudGltZVdvcmtlclJlc3BvbnNlEhoKCXdvcmtlcl9pZBgBIAEoCUIHukgEcgIQASJzChZOb3RpZmljYXRpb25BdHRhY2htZW50EhkKCGZpbGVuYW1lGAEgASgJQge6SARyAhABEh8KDmNvbnRlbnRfYmFzZTY0GAIgASgJQge6SARyAhABEh0KDGNvbnRlbnRfdHlwZRgDIAEoCUIHukgEcgIQAWIGcHJvdG8z", [file_buf_validate_validate, file_dataforge_protocol_enums]);

/**
 * @generated from message dataforge.runtime.EmptyRequest
 */
export type EmptyRequest = Message<"dataforge.runtime.EmptyRequest"> & {
  /**
   * Recovery RPCs use this optional field to direct work to one namespace;
   * existing empty-request callers remain valid.
   *
   * @generated from field: string namespace = 1;
   */
  namespace: string;
};

/**
 * @generated from message dataforge.runtime.EmptyRequest
 */
export type EmptyRequestJson = {
  /**
   * Recovery RPCs use this optional field to direct work to one namespace;
   * existing empty-request callers remain valid.
   *
   * @generated from field: string namespace = 1;
   */
  namespace?: string;
};

/**
 * Describes the message dataforge.runtime.EmptyRequest.
 * Use `create(EmptyRequestSchema)` to create a new message.
 */
export const EmptyRequestSchema: GenMessage<EmptyRequest, {jsonType: EmptyRequestJson}> = /*@__PURE__*/
  messageDesc(file_dataforge_protocol_common, 0);

/**
 * @generated from message dataforge.runtime.RuntimeWorkerRequest
 */
export type RuntimeWorkerRequest = Message<"dataforge.runtime.RuntimeWorkerRequest"> & {
  /**
   * @generated from field: string worker_id = 1;
   */
  workerId: string;

  /**
   * @generated from field: int32 protocol_version = 2;
   */
  protocolVersion: number;

  /**
   * @generated from field: repeated dataforge.runtime.ComputeRequestKind allowed_compute_request_kinds = 3;
   */
  allowedComputeRequestKinds: ComputeRequestKind[];

  /**
   * Claim RPCs are directed to one namespace. The worker gets this value from
   * the matching runtime notification or from its bounded recovery cursor;
   * the backend must never scan every tenant to satisfy one claim.
   *
   * @generated from field: string target_namespace = 5;
   */
  targetNamespace: string;
};

/**
 * @generated from message dataforge.runtime.RuntimeWorkerRequest
 */
export type RuntimeWorkerRequestJson = {
  /**
   * @generated from field: string worker_id = 1;
   */
  workerId?: string;

  /**
   * @generated from field: int32 protocol_version = 2;
   */
  protocolVersion?: number;

  /**
   * @generated from field: repeated dataforge.runtime.ComputeRequestKind allowed_compute_request_kinds = 3;
   */
  allowedComputeRequestKinds?: ComputeRequestKindJson[];

  /**
   * Claim RPCs are directed to one namespace. The worker gets this value from
   * the matching runtime notification or from its bounded recovery cursor;
   * the backend must never scan every tenant to satisfy one claim.
   *
   * @generated from field: string target_namespace = 5;
   */
  targetNamespace?: string;
};

/**
 * Describes the message dataforge.runtime.RuntimeWorkerRequest.
 * Use `create(RuntimeWorkerRequestSchema)` to create a new message.
 */
export const RuntimeWorkerRequestSchema: GenMessage<RuntimeWorkerRequest, {jsonType: RuntimeWorkerRequestJson}> = /*@__PURE__*/
  messageDesc(file_dataforge_protocol_common, 1);

/**
 * @generated from message dataforge.runtime.RuntimeWorkerResponse
 */
export type RuntimeWorkerResponse = Message<"dataforge.runtime.RuntimeWorkerResponse"> & {
  /**
   * @generated from field: string worker_id = 1;
   */
  workerId: string;
};

/**
 * @generated from message dataforge.runtime.RuntimeWorkerResponse
 */
export type RuntimeWorkerResponseJson = {
  /**
   * @generated from field: string worker_id = 1;
   */
  workerId?: string;
};

/**
 * Describes the message dataforge.runtime.RuntimeWorkerResponse.
 * Use `create(RuntimeWorkerResponseSchema)` to create a new message.
 */
export const RuntimeWorkerResponseSchema: GenMessage<RuntimeWorkerResponse, {jsonType: RuntimeWorkerResponseJson}> = /*@__PURE__*/
  messageDesc(file_dataforge_protocol_common, 2);

/**
 * @generated from message dataforge.runtime.NotificationAttachment
 */
export type NotificationAttachment = Message<"dataforge.runtime.NotificationAttachment"> & {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * @generated from field: string content_base64 = 2;
   */
  contentBase64: string;

  /**
   * @generated from field: string content_type = 3;
   */
  contentType: string;
};

/**
 * @generated from message dataforge.runtime.NotificationAttachment
 */
export type NotificationAttachmentJson = {
  /**
   * @generated from field: string filename = 1;
   */
  filename?: string;

  /**
   * @generated from field: string content_base64 = 2;
   */
  contentBase64?: string;

  /**
   * @generated from field: string content_type = 3;
   */
  contentType?: string;
};

/**
 * Describes the message dataforge.runtime.NotificationAttachment.
 * Use `create(NotificationAttachmentSchema)` to create a new message.
 */
export const NotificationAttachmentSchema: GenMessage<NotificationAttachment, {jsonType: NotificationAttachmentJson}> = /*@__PURE__*/
  messageDesc(file_dataforge_protocol_common, 3);

