// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,json_types=true"
// @generated from file dataforge_protocol/runtime_coordinator.proto (package dataforge.runtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../buf/validate/validate_pb";
import type { EmptyRequestSchema } from "./common_pb";
import { file_dataforge_protocol_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dataforge_protocol/runtime_coordinator.proto.
 */
export const file_dataforge_protocol_runtime_coordinator: GenFile = /*@__PURE__*/
  fileDesc("CixkYXRhZm9yZ2VfcHJvdG9jb2wvcnVudGltZV9jb29yZGluYXRvci5wcm90bxIRZGF0YWZvcmdlLnJ1bnRpbWUiQgojUnVudGltZUNvb3JkaW5hdG9yR2VuZXJhdGlvblJlcXVlc3QSGwoKZ2VuZXJhdGlvbhgBIAEoA0IHukgEIgIgACJDCiRSdW50aW1lQ29vcmRpbmF0b3JHZW5lcmF0aW9uUmVzcG9uc2USGwoKZ2VuZXJhdGlvbhgBIAEoA0IHukgEIgIgADKiAgoZUnVudGltZUNvb3JkaW5hdG9yU2VydmljZRJ0ChhHZXRDb29yZGluYXRvckdlbmVyYXRpb24SHy5kYXRhZm9yZ2UucnVudGltZS5FbXB0eVJlcXVlc3QaNy5kYXRhZm9yZ2UucnVudGltZS5SdW50aW1lQ29vcmRpbmF0b3JHZW5lcmF0aW9uUmVzcG9uc2USjgEKG0Fzc2VydENvb3JkaW5hdG9yR2VuZXJhdGlvbhI2LmRhdGFmb3JnZS5ydW50aW1lLlJ1bnRpbWVDb29yZGluYXRvckdlbmVyYXRpb25SZXF1ZXN0GjcuZGF0YWZvcmdlLnJ1bnRpbWUuUnVudGltZUNvb3JkaW5hdG9yR2VuZXJhdGlvblJlc3BvbnNlYgZwcm90bzM", [file_buf_validate_validate, file_dataforge_protocol_common]);

/**
 * @generated from message dataforge.runtime.RuntimeCoordinatorGenerationRequest
 */
export type RuntimeCoordinatorGenerationRequest = Message<"dataforge.runtime.RuntimeCoordinatorGenerationRequest"> & {
  /**
   * @generated from field: int64 generation = 1;
   */
  generation: bigint;
};

/**
 * @generated from message dataforge.runtime.RuntimeCoordinatorGenerationRequest
 */
export type RuntimeCoordinatorGenerationRequestJson = {
  /**
   * @generated from field: int64 generation = 1;
   */
  generation?: string;
};

/**
 * Describes the message dataforge.runtime.RuntimeCoordinatorGenerationRequest.
 * Use `create(RuntimeCoordinatorGenerationRequestSchema)` to create a new message.
 */
export const RuntimeCoordinatorGenerationRequestSchema: GenMessage<RuntimeCoordinatorGenerationRequest, {jsonType: RuntimeCoordinatorGenerationRequestJson}> = /*@__PURE__*/
  messageDesc(file_dataforge_protocol_runtime_coordinator, 0);

/**
 * @generated from message dataforge.runtime.RuntimeCoordinatorGenerationResponse
 */
export type RuntimeCoordinatorGenerationResponse = Message<"dataforge.runtime.RuntimeCoordinatorGenerationResponse"> & {
  /**
   * @generated from field: int64 generation = 1;
   */
  generation: bigint;
};

/**
 * @generated from message dataforge.runtime.RuntimeCoordinatorGenerationResponse
 */
export type RuntimeCoordinatorGenerationResponseJson = {
  /**
   * @generated from field: int64 generation = 1;
   */
  generation?: string;
};

/**
 * Describes the message dataforge.runtime.RuntimeCoordinatorGenerationResponse.
 * Use `create(RuntimeCoordinatorGenerationResponseSchema)` to create a new message.
 */
export const RuntimeCoordinatorGenerationResponseSchema: GenMessage<RuntimeCoordinatorGenerationResponse, {jsonType: RuntimeCoordinatorGenerationResponseJson}> = /*@__PURE__*/
  messageDesc(file_dataforge_protocol_runtime_coordinator, 1);

/**
 * @generated from service dataforge.runtime.RuntimeCoordinatorService
 */
export const RuntimeCoordinatorService: GenService<{
  /**
   * @generated from rpc dataforge.runtime.RuntimeCoordinatorService.GetCoordinatorGeneration
   */
  getCoordinatorGeneration: {
    methodKind: "unary";
    input: typeof EmptyRequestSchema;
    output: typeof RuntimeCoordinatorGenerationResponseSchema;
  },
  /**
   * @generated from rpc dataforge.runtime.RuntimeCoordinatorService.AssertCoordinatorGeneration
   */
  assertCoordinatorGeneration: {
    methodKind: "unary";
    input: typeof RuntimeCoordinatorGenerationRequestSchema;
    output: typeof RuntimeCoordinatorGenerationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_dataforge_protocol_runtime_coordinator, 0);

