// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,json_types=true"
// @generated from file dataforge_protocol/runtime.proto (package dataforge.runtime, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../buf/validate/validate_pb";
import type { BuildEvent, BuildEventJson, ComputeCommandEnvelope, ComputeCommandEnvelopeJson, ComputeResponseEnvelope, ComputeResponseEnvelopeJson } from "./compute_pb";
import { file_dataforge_protocol_compute } from "./compute_pb";
import type { ErrorInfo, ErrorInfoJson } from "./errors_pb";
import { file_dataforge_protocol_errors } from "./errors_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dataforge_protocol/runtime.proto.
 */
export const file_dataforge_protocol_runtime: GenFile = /*@__PURE__*/
  fileDesc("CiBkYXRhZm9yZ2VfcHJvdG9jb2wvcnVudGltZS5wcm90bxIRZGF0YWZvcmdlLnJ1bnRpbWUivQIKDFJ1bnRpbWVFdmVudBIqCgluYW1lc3BhY2UYASABKAlCF7pIFHISMhBeW2EtekEtWjAtOV8tXSskEi4KBWJ1aWxkGAIgASgLMh0uZGF0YWZvcmdlLnJ1bnRpbWUuQnVpbGRFdmVudEgAEkQKD2NvbXB1dGVfY29tbWFuZBgDIAEoCzIpLmRhdGFmb3JnZS5ydW50aW1lLkNvbXB1dGVDb21tYW5kRW52ZWxvcGVIABJGChBjb21wdXRlX3Jlc3BvbnNlGAQgASgLMiouZGF0YWZvcmdlLnJ1bnRpbWUuQ29tcHV0ZVJlc3BvbnNlRW52ZWxvcGVIABItCgVlcnJvchgFIAEoCzIcLmRhdGFmb3JnZS5ydW50aW1lLkVycm9ySW5mb0gAQgkKB3BheWxvYWRKBAgGEAdSA3Jhd2IGcHJvdG8z", [file_buf_validate_validate, file_dataforge_protocol_compute, file_dataforge_protocol_errors]);

/**
 * @generated from message dataforge.runtime.RuntimeEvent
 */
export type RuntimeEvent = Message<"dataforge.runtime.RuntimeEvent"> & {
  /**
   * @generated from field: string namespace = 1;
   */
  namespace: string;

  /**
   * @generated from oneof dataforge.runtime.RuntimeEvent.payload
   */
  payload: {
    /**
     * @generated from field: dataforge.runtime.BuildEvent build = 2;
     */
    value: BuildEvent;
    case: "build";
  } | {
    /**
     * @generated from field: dataforge.runtime.ComputeCommandEnvelope compute_command = 3;
     */
    value: ComputeCommandEnvelope;
    case: "computeCommand";
  } | {
    /**
     * @generated from field: dataforge.runtime.ComputeResponseEnvelope compute_response = 4;
     */
    value: ComputeResponseEnvelope;
    case: "computeResponse";
  } | {
    /**
     * @generated from field: dataforge.runtime.ErrorInfo error = 5;
     */
    value: ErrorInfo;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message dataforge.runtime.RuntimeEvent
 */
export type RuntimeEventJson = {
  /**
   * @generated from field: string namespace = 1;
   */
  namespace?: string;

  /**
   * @generated from field: dataforge.runtime.BuildEvent build = 2;
   */
  build?: BuildEventJson;

  /**
   * @generated from field: dataforge.runtime.ComputeCommandEnvelope compute_command = 3;
   */
  computeCommand?: ComputeCommandEnvelopeJson;

  /**
   * @generated from field: dataforge.runtime.ComputeResponseEnvelope compute_response = 4;
   */
  computeResponse?: ComputeResponseEnvelopeJson;

  /**
   * @generated from field: dataforge.runtime.ErrorInfo error = 5;
   */
  error?: ErrorInfoJson;
};

/**
 * Describes the message dataforge.runtime.RuntimeEvent.
 * Use `create(RuntimeEventSchema)` to create a new message.
 */
export const RuntimeEventSchema: GenMessage<RuntimeEvent, {jsonType: RuntimeEventJson}> = /*@__PURE__*/
  messageDesc(file_dataforge_protocol_runtime, 0);

