# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataforge_protocol/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dataforge_protocol/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64\x61taforge_protocol/common.proto\x12\x11\x64\x61taforge.runtime\x1a\x1b\x62uf/validate/validate.proto\"\x0e\n\x0c\x45mptyRequest\"<\n\x14RuntimeWorkerRequest\x12$\n\tworker_id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08workerId\"=\n\x15RuntimeWorkerResponse\x12$\n\tworker_id\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08workerId\"\x99\x01\n\x16NotificationAttachment\x12#\n\x08\x66ilename\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08\x66ilename\x12.\n\x0e\x63ontent_base64\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\rcontentBase64\x12*\n\x0c\x63ontent_type\x18\x03 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x0b\x63ontentTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataforge_protocol.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNTIMEWORKERREQUEST'].fields_by_name['worker_id']._loaded_options = None
  _globals['_RUNTIMEWORKERREQUEST'].fields_by_name['worker_id']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_RUNTIMEWORKERRESPONSE'].fields_by_name['worker_id']._loaded_options = None
  _globals['_RUNTIMEWORKERRESPONSE'].fields_by_name['worker_id']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_NOTIFICATIONATTACHMENT'].fields_by_name['filename']._loaded_options = None
  _globals['_NOTIFICATIONATTACHMENT'].fields_by_name['filename']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_NOTIFICATIONATTACHMENT'].fields_by_name['content_base64']._loaded_options = None
  _globals['_NOTIFICATIONATTACHMENT'].fields_by_name['content_base64']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_NOTIFICATIONATTACHMENT'].fields_by_name['content_type']._loaded_options = None
  _globals['_NOTIFICATIONATTACHMENT'].fields_by_name['content_type']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_EMPTYREQUEST']._serialized_start=83
  _globals['_EMPTYREQUEST']._serialized_end=97
  _globals['_RUNTIMEWORKERREQUEST']._serialized_start=99
  _globals['_RUNTIMEWORKERREQUEST']._serialized_end=159
  _globals['_RUNTIMEWORKERRESPONSE']._serialized_start=161
  _globals['_RUNTIMEWORKERRESPONSE']._serialized_end=222
  _globals['_NOTIFICATIONATTACHMENT']._serialized_start=225
  _globals['_NOTIFICATIONATTACHMENT']._serialized_end=378
# @@protoc_insertion_point(module_scope)
