# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from dataforge_protocol import common_pb2 as dataforge__protocol_dot_common__pb2
from dataforge_protocol import iceberg_pb2 as dataforge__protocol_dot_iceberg__pb2


class IcebergServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveMetadataPath = channel.unary_unary(
                '/dataforge.runtime.IcebergService/ResolveMetadataPath',
                request_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.SerializeToString,
                response_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergMetadataPathResponse.FromString,
                _registered_method=True)
        self.ResolveBranchMetadataPath = channel.unary_unary(
                '/dataforge.runtime.IcebergService/ResolveBranchMetadataPath',
                request_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.SerializeToString,
                response_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergMetadataPathResponse.FromString,
                _registered_method=True)
        self.SyncSchema = channel.unary_unary(
                '/dataforge.runtime.IcebergService/SyncSchema',
                request_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergSchemaSyncRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                _registered_method=True)
        self.ListSnapshots = channel.unary_unary(
                '/dataforge.runtime.IcebergService/ListSnapshots',
                request_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.SerializeToString,
                response_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotsResponse.FromString,
                _registered_method=True)
        self.ScanSnapshot = channel.unary_unary(
                '/dataforge.runtime.IcebergService/ScanSnapshot',
                request_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotScanRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotScanResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/dataforge.runtime.IcebergService/DeleteSnapshot',
                request_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotDeleteRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotDeleteResponse.FromString,
                _registered_method=True)


class IcebergServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ResolveMetadataPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveBranchMetadataPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IcebergServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveMetadataPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveMetadataPath,
                    request_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.FromString,
                    response_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergMetadataPathResponse.SerializeToString,
            ),
            'ResolveBranchMetadataPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveBranchMetadataPath,
                    request_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.FromString,
                    response_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergMetadataPathResponse.SerializeToString,
            ),
            'SyncSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncSchema,
                    request_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergSchemaSyncRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.FromString,
                    response_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotsResponse.SerializeToString,
            ),
            'ScanSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanSnapshot,
                    request_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotScanRequest.FromString,
                    response_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotScanResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotDeleteRequest.FromString,
                    response_serializer=dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataforge.runtime.IcebergService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataforge.runtime.IcebergService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IcebergService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResolveMetadataPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.IcebergService/ResolveMetadataPath',
            dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.SerializeToString,
            dataforge__protocol_dot_iceberg__pb2.IcebergMetadataPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveBranchMetadataPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.IcebergService/ResolveBranchMetadataPath',
            dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.SerializeToString,
            dataforge__protocol_dot_iceberg__pb2.IcebergMetadataPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.IcebergService/SyncSchema',
            dataforge__protocol_dot_iceberg__pb2.IcebergSchemaSyncRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.IcebergService/ListSnapshots',
            dataforge__protocol_dot_iceberg__pb2.IcebergTableRef.SerializeToString,
            dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.IcebergService/ScanSnapshot',
            dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotScanRequest.SerializeToString,
            dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.IcebergService/DeleteSnapshot',
            dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotDeleteRequest.SerializeToString,
            dataforge__protocol_dot_iceberg__pb2.IcebergSnapshotDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
