# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dataforge_protocol import common_pb2 as dataforge__protocol_dot_common__pb2
from dataforge_protocol import object_store_pb2 as dataforge__protocol_dot_object__store__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dataforge_protocol/object_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectStoreServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyUrl = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/ClassifyUrl',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrlClassificationRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrlClassificationResponse.FromString,
                _registered_method=True)
        self.BuildUrl = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/BuildUrl',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStorePathParts.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                _registered_method=True)
        self.JoinUrl = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/JoinUrl',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreJoinRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                _registered_method=True)
        self.StorageOptions = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/StorageOptions',
                request_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreStorageOptionsResponse.FromString,
                _registered_method=True)
        self.EnsureBucket = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/EnsureBucket',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreBucket.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                _registered_method=True)
        self.UploadObject = channel.stream_unary(
                '/dataforge.runtime.ObjectStoreService/UploadObject',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUploadRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                _registered_method=True)
        self.DownloadObject = channel.unary_stream(
                '/dataforge.runtime.ObjectStoreService/DownloadObject',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreTransferChunk.FromString,
                _registered_method=True)
        self.DeleteObject = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/DeleteObject',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/Exists',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreExistsResponse.FromString,
                _registered_method=True)
        self.ListPrefixes = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/ListPrefixes',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStorePrefixesResponse.FromString,
                _registered_method=True)
        self.ListMetadataFiles = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/ListMetadataFiles',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
                response_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreMetadataFilesResponse.FromString,
                _registered_method=True)
        self.DeletePrefix = channel.unary_unary(
                '/dataforge.runtime.ObjectStoreService/DeletePrefix',
                request_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                _registered_method=True)


class ObjectStoreServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ClassifyUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadObject(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrefixes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMetadataFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyUrl,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrlClassificationRequest.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrlClassificationResponse.SerializeToString,
            ),
            'BuildUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildUrl,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStorePathParts.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            ),
            'JoinUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinUrl,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreJoinRequest.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            ),
            'StorageOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageOptions,
                    request_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreStorageOptionsResponse.SerializeToString,
            ),
            'EnsureBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureBucket,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreBucket.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            ),
            'UploadObject': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadObject,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUploadRequest.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            ),
            'DownloadObject': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadObject,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreTransferChunk.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreExistsResponse.SerializeToString,
            ),
            'ListPrefixes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrefixes,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStorePrefixesResponse.SerializeToString,
            ),
            'ListMetadataFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMetadataFiles,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                    response_serializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreMetadataFilesResponse.SerializeToString,
            ),
            'DeletePrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePrefix,
                    request_deserializer=dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataforge.runtime.ObjectStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataforge.runtime.ObjectStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectStoreService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/ClassifyUrl',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrlClassificationRequest.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrlClassificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/BuildUrl',
            dataforge__protocol_dot_object__store__pb2.ObjectStorePathParts.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/JoinUrl',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreJoinRequest.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StorageOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/StorageOptions',
            dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStoreStorageOptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/EnsureBucket',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreBucket.SerializeToString,
            dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadObject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dataforge.runtime.ObjectStoreService/UploadObject',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUploadRequest.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/DownloadObject',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStoreTransferChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/DeleteObject',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/Exists',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStoreExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrefixes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/ListPrefixes',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStorePrefixesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMetadataFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/ListMetadataFiles',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            dataforge__protocol_dot_object__store__pb2.ObjectStoreMetadataFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.ObjectStoreService/DeletePrefix',
            dataforge__protocol_dot_object__store__pb2.ObjectStoreUrl.SerializeToString,
            dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
