from __future__ import annotations

from backend_core.exceptions import AppError
from dataforge_protocol import errors_pb2

ERROR_CODE_STATUS_MAP: dict[int, int] = {
    errors_pb2.ERROR_CODE_DATASOURCE_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_JOB_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_ANALYSIS_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_ANALYSIS_VERSION_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_ENGINE_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_ENGINE_RUN_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_FILE_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_STEP_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_SCHEDULE_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_UDF_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_HEALTHCHECK_NOT_FOUND: 404,
    errors_pb2.ERROR_CODE_PIPELINE_VALIDATION_ERROR: 400,
    errors_pb2.ERROR_CODE_FILE_VALIDATION_ERROR: 400,
    errors_pb2.ERROR_CODE_UNSUPPORTED_EXPORT_FORMAT: 400,
    errors_pb2.ERROR_CODE_SCHEDULE_VALIDATION_ERROR: 400,
    errors_pb2.ERROR_CODE_DATASOURCE_VALIDATION_ERROR: 400,
    errors_pb2.ERROR_CODE_ANALYSIS_VALIDATION_ERROR: 400,
    errors_pb2.ERROR_CODE_UDF_VALIDATION_ERROR: 400,
    errors_pb2.ERROR_CODE_HEALTHCHECK_VALIDATION_ERROR: 400,
    errors_pb2.ERROR_CODE_INVALID_ID: 400,
    errors_pb2.ERROR_CODE_ENGINE_RUN_COMPARISON_ERROR: 400,
    errors_pb2.ERROR_CODE_PROVIDER_UNLINK_ERROR: 400,
    errors_pb2.ERROR_CODE_OAUTH_ERROR: 400,
    errors_pb2.ERROR_CODE_TOKEN_EXPIRED: 400,
    errors_pb2.ERROR_CODE_TOKEN_INVALID: 400,
    errors_pb2.ERROR_CODE_ANALYSIS_CYCLE_ERROR: 422,
    errors_pb2.ERROR_CODE_DATASOURCE_CONNECTION_ERROR: 502,
    errors_pb2.ERROR_CODE_DATASOURCE_SNAPSHOT_ERROR: 409,
    errors_pb2.ERROR_CODE_ENGINE_BUSY: 409,
    errors_pb2.ERROR_CODE_FILE_SIZE_EXCEEDED: 413,
    errors_pb2.ERROR_CODE_PIPELINE_EXECUTION_ERROR: 500,
    errors_pb2.ERROR_CODE_SETTINGS_CONFIGURATION_ERROR: 500,
    errors_pb2.ERROR_CODE_ENGINE_START_ERROR: 500,
    errors_pb2.ERROR_CODE_INVALID_CREDENTIALS: 401,
    errors_pb2.ERROR_CODE_SESSION_EXPIRED: 401,
    errors_pb2.ERROR_CODE_ACCOUNT_DISABLED: 403,
    errors_pb2.ERROR_CODE_DEFAULT_USER_DELETION_FORBIDDEN: 403,
    errors_pb2.ERROR_CODE_EMAIL_ALREADY_EXISTS: 409,
}


def status_for_app_error(exc: AppError) -> int:
    return ERROR_CODE_STATUS_MAP.get(exc.error_code_value, 500)
