# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dataforge_protocol import common_pb2 as dataforge__protocol_dot_common__pb2
from dataforge_protocol import runtime_coordinator_pb2 as dataforge__protocol_dot_runtime__coordinator__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dataforge_protocol/runtime_coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeCoordinatorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoordinatorGeneration = channel.unary_unary(
                '/dataforge.runtime.RuntimeCoordinatorService/GetCoordinatorGeneration',
                request_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationResponse.FromString,
                _registered_method=True)
        self.AssertCoordinatorGeneration = channel.unary_unary(
                '/dataforge.runtime.RuntimeCoordinatorService/AssertCoordinatorGeneration',
                request_serializer=dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationResponse.FromString,
                _registered_method=True)


class RuntimeCoordinatorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCoordinatorGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssertCoordinatorGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeCoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoordinatorGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoordinatorGeneration,
                    request_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationResponse.SerializeToString,
            ),
            'AssertCoordinatorGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.AssertCoordinatorGeneration,
                    request_deserializer=dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationRequest.FromString,
                    response_serializer=dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataforge.runtime.RuntimeCoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataforge.runtime.RuntimeCoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeCoordinatorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCoordinatorGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.RuntimeCoordinatorService/GetCoordinatorGeneration',
            dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssertCoordinatorGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.RuntimeCoordinatorService/AssertCoordinatorGeneration',
            dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationRequest.SerializeToString,
            dataforge__protocol_dot_runtime__coordinator__pb2.RuntimeCoordinatorGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
