# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dataforge_protocol import common_pb2 as dataforge__protocol_dot_common__pb2
from dataforge_protocol import worker_runtime_pb2 as dataforge__protocol_dot_worker__runtime__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dataforge_protocol/worker_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerRuntimeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/RegisterWorker',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.RuntimeWorkerRegisterRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.HeartbeatWorker = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/HeartbeatWorker',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.RuntimeWorkerHeartbeatRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.StopWorker = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/StopWorker',
                request_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.ClaimBuildJob = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ClaimBuildJob',
                request_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimBuildJobResponse.FromString,
                _registered_method=True)
        self.RenewBuildJobLease = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/RenewBuildJobLease',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildJobClaimRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewBuildJobLeaseResponse.FromString,
                _registered_method=True)
        self.ClaimComputeRequest = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ClaimComputeRequest',
                request_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimComputeRequestResponse.FromString,
                _registered_method=True)
        self.RenewComputeRequestLeases = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/RenewComputeRequestLeases',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewComputeRequestLeasesRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewComputeRequestLeasesResponse.FromString,
                _registered_method=True)
        self.CompleteComputeRequest = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/CompleteComputeRequest',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerCompleteComputeRequestRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.FailComputeRequest = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/FailComputeRequest',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFailComputeRequestRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.PublishDatasourceCreate = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/PublishDatasourceCreate',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceCreateRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceCreateResponse.FromString,
                _registered_method=True)
        self.PublishDatasourceIngest = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/PublishDatasourceIngest',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceIngestRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceIngestResponse.FromString,
                _registered_method=True)
        self.PublishDatasourceSchemaCache = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/PublishDatasourceSchemaCache',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceSchemaCacheRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceSchemaCacheResponse.FromString,
                _registered_method=True)
        self.RegisterDatasourceStage = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/RegisterDatasourceStage',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRegisterDatasourceStageRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.ClaimStorageCleanup = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ClaimStorageCleanup',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimStorageCleanupRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerStorageCleanupClaimsResponse.FromString,
                _registered_method=True)
        self.AuthorizeStorageCleanup = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/AuthorizeStorageCleanup',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerStorageCleanupClaimRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.CompleteStorageCleanup = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/CompleteStorageCleanup',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerCompleteStorageCleanupRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.GetDatasourceMetadata = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetDatasourceMetadata',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerDatasourceMetadataRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerDatasourceMetadataResponse.FromString,
                _registered_method=True)
        self.GetUdfCodes = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetUdfCodes',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUdfCodesRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUdfCodesResponse.FromString,
                _registered_method=True)
        self.GetComputeWorkerCredentials = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetComputeWorkerCredentials',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerCredentialsRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerCredentialsResponse.FromString,
                _registered_method=True)
        self.GetAnalysisMetadata = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetAnalysisMetadata',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerAnalysisMetadataRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerAnalysisMetadataResponse.FromString,
                _registered_method=True)
        self.GetBuildCancelStatus = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetBuildCancelStatus',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildCancelStatusRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildCancelStatusResponse.FromString,
                _registered_method=True)
        self.UpdateBuildResult = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/UpdateBuildResult',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUpdateBuildResultRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.UpsertOutputDatasource = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/UpsertOutputDatasource',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUpsertOutputDatasourceRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUpsertOutputDatasourceResponse.FromString,
                _registered_method=True)
        self.ListHealthChecks = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ListHealthChecks',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerListHealthChecksRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerListHealthChecksResponse.FromString,
                _registered_method=True)
        self.RecordHealthCheckResults = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/RecordHealthCheckResults',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRecordHealthCheckResultsRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
                _registered_method=True)
        self.CreateComputeWorkerRun = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/CreateComputeWorkerRun',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerCreateComputeWorkerRunRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.IdResponse.FromString,
                _registered_method=True)
        self.UpdateComputeWorkerRun = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/UpdateComputeWorkerRun',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUpdateComputeWorkerRunRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.IdResponse.FromString,
                _registered_method=True)
        self.GetComputeWorkerRunState = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetComputeWorkerRunState',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerRunStateRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerRunStateResponse.FromString,
                _registered_method=True)
        self.FailBuildJob = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/FailBuildJob',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFailBuildJobRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.FinalizeBuildJob = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/FinalizeBuildJob',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeBuildJobRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.ReleaseBuildWorkerJobs = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ReleaseBuildWorkerJobs',
                request_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
                _registered_method=True)
        self.GetQueuedBuildJobCount = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetQueuedBuildJobCount',
                request_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
                _registered_method=True)
        self.ReconcileExpiredBuildJobs = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ReconcileExpiredBuildJobs',
                request_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
                _registered_method=True)
        self.ReconcileExpiredComputeRequests = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ReconcileExpiredComputeRequests',
                request_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
                _registered_method=True)
        self.GetIdleBuildWorkerPids = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetIdleBuildWorkerPids',
                request_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerIdlePidsResponse.FromString,
                _registered_method=True)
        self.ListPendingRuntimeWorkNamespaces = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ListPendingRuntimeWorkNamespaces',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPendingRuntimeWorkNamespacesRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerNamespacesResponse.FromString,
                _registered_method=True)
        self.PersistBuildEvent = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/PersistBuildEvent',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistBuildEventRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistBuildEventResponse.FromString,
                _registered_method=True)
        self.StartBuildRun = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/StartBuildRun',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerStartBuildRunRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerStartBuildRunResponse.FromString,
                _registered_method=True)
        self.PersistComputeWorkerSnapshot = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/PersistComputeWorkerSnapshot',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistComputeWorkerSnapshotRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
                _registered_method=True)
        self.ListPendingDatasourceDeletes = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/ListPendingDatasourceDeletes',
                request_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPendingDatasourceDeletesResponse.FromString,
                _registered_method=True)
        self.FinalizeDatasourceDelete = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/FinalizeDatasourceDelete',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeDatasourceDeleteRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeDatasourceDeleteResponse.FromString,
                _registered_method=True)
        self.GetTelegramSettings = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetTelegramSettings',
                request_serializer=dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramSettingsResponse.FromString,
                _registered_method=True)
        self.SendEmail = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/SendEmail',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerSendEmailRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.SendTelegram = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/SendTelegram',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerSendTelegramRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.GenerateAI = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GenerateAI',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerGenerateAIRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerGenerateAIResponse.FromString,
                _registered_method=True)
        self.GetTelegramTargets = channel.unary_unary(
                '/dataforge.runtime.WorkerRuntimeService/GetTelegramTargets',
                request_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramTargetsRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramTargetsResponse.FromString,
                _registered_method=True)


class WorkerRuntimeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimBuildJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewBuildJobLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimComputeRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewComputeRequestLeases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteComputeRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailComputeRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishDatasourceCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishDatasourceIngest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishDatasourceSchemaCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDatasourceStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimStorageCleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeStorageCleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteStorageCleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasourceMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUdfCodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComputeWorkerCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalysisMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuildCancelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBuildResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertOutputDatasource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHealthChecks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordHealthCheckResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComputeWorkerRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComputeWorkerRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComputeWorkerRunState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailBuildJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeBuildJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseBuildWorkerJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueuedBuildJobCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileExpiredBuildJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileExpiredComputeRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdleBuildWorkerPids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPendingRuntimeWorkNamespaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersistBuildEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBuildRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersistComputeWorkerSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPendingDatasourceDeletes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeDatasourceDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelegramSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTelegram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelegramTargets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.RuntimeWorkerRegisterRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'HeartbeatWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatWorker,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.RuntimeWorkerHeartbeatRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'StopWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.StopWorker,
                    request_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'ClaimBuildJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimBuildJob,
                    request_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimBuildJobResponse.SerializeToString,
            ),
            'RenewBuildJobLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewBuildJobLease,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildJobClaimRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewBuildJobLeaseResponse.SerializeToString,
            ),
            'ClaimComputeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimComputeRequest,
                    request_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimComputeRequestResponse.SerializeToString,
            ),
            'RenewComputeRequestLeases': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewComputeRequestLeases,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewComputeRequestLeasesRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewComputeRequestLeasesResponse.SerializeToString,
            ),
            'CompleteComputeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteComputeRequest,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerCompleteComputeRequestRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'FailComputeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.FailComputeRequest,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFailComputeRequestRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'PublishDatasourceCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishDatasourceCreate,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceCreateRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceCreateResponse.SerializeToString,
            ),
            'PublishDatasourceIngest': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishDatasourceIngest,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceIngestRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceIngestResponse.SerializeToString,
            ),
            'PublishDatasourceSchemaCache': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishDatasourceSchemaCache,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceSchemaCacheRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceSchemaCacheResponse.SerializeToString,
            ),
            'RegisterDatasourceStage': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDatasourceStage,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRegisterDatasourceStageRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.SerializeToString,
            ),
            'ClaimStorageCleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimStorageCleanup,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimStorageCleanupRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerStorageCleanupClaimsResponse.SerializeToString,
            ),
            'AuthorizeStorageCleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeStorageCleanup,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerStorageCleanupClaimRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.SerializeToString,
            ),
            'CompleteStorageCleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteStorageCleanup,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerCompleteStorageCleanupRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.SerializeToString,
            ),
            'GetDatasourceMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasourceMetadata,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerDatasourceMetadataRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerDatasourceMetadataResponse.SerializeToString,
            ),
            'GetUdfCodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUdfCodes,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUdfCodesRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUdfCodesResponse.SerializeToString,
            ),
            'GetComputeWorkerCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComputeWorkerCredentials,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerCredentialsRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerCredentialsResponse.SerializeToString,
            ),
            'GetAnalysisMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysisMetadata,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerAnalysisMetadataRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerAnalysisMetadataResponse.SerializeToString,
            ),
            'GetBuildCancelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuildCancelStatus,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildCancelStatusRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildCancelStatusResponse.SerializeToString,
            ),
            'UpdateBuildResult': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBuildResult,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUpdateBuildResultRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'UpsertOutputDatasource': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertOutputDatasource,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUpsertOutputDatasourceRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUpsertOutputDatasourceResponse.SerializeToString,
            ),
            'ListHealthChecks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHealthChecks,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerListHealthChecksRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerListHealthChecksResponse.SerializeToString,
            ),
            'RecordHealthCheckResults': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordHealthCheckResults,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerRecordHealthCheckResultsRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.SerializeToString,
            ),
            'CreateComputeWorkerRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComputeWorkerRun,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerCreateComputeWorkerRunRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.IdResponse.SerializeToString,
            ),
            'UpdateComputeWorkerRun': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComputeWorkerRun,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerUpdateComputeWorkerRunRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.IdResponse.SerializeToString,
            ),
            'GetComputeWorkerRunState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComputeWorkerRunState,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerRunStateRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerRunStateResponse.SerializeToString,
            ),
            'FailBuildJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FailBuildJob,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFailBuildJobRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.SerializeToString,
            ),
            'FinalizeBuildJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeBuildJob,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeBuildJobRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.SerializeToString,
            ),
            'ReleaseBuildWorkerJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseBuildWorkerJobs,
                    request_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.SerializeToString,
            ),
            'GetQueuedBuildJobCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueuedBuildJobCount,
                    request_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.SerializeToString,
            ),
            'ReconcileExpiredBuildJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileExpiredBuildJobs,
                    request_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.SerializeToString,
            ),
            'ReconcileExpiredComputeRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileExpiredComputeRequests,
                    request_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.SerializeToString,
            ),
            'GetIdleBuildWorkerPids': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdleBuildWorkerPids,
                    request_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerIdlePidsResponse.SerializeToString,
            ),
            'ListPendingRuntimeWorkNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPendingRuntimeWorkNamespaces,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPendingRuntimeWorkNamespacesRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerNamespacesResponse.SerializeToString,
            ),
            'PersistBuildEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PersistBuildEvent,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistBuildEventRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistBuildEventResponse.SerializeToString,
            ),
            'StartBuildRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBuildRun,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerStartBuildRunRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerStartBuildRunResponse.SerializeToString,
            ),
            'PersistComputeWorkerSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.PersistComputeWorkerSnapshot,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistComputeWorkerSnapshotRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.CountResponse.SerializeToString,
            ),
            'ListPendingDatasourceDeletes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPendingDatasourceDeletes,
                    request_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerPendingDatasourceDeletesResponse.SerializeToString,
            ),
            'FinalizeDatasourceDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeDatasourceDelete,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeDatasourceDeleteRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeDatasourceDeleteResponse.SerializeToString,
            ),
            'GetTelegramSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelegramSettings,
                    request_deserializer=dataforge__protocol_dot_common__pb2.EmptyRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramSettingsResponse.SerializeToString,
            ),
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerSendEmailRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.SerializeToString,
            ),
            'SendTelegram': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTelegram,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerSendTelegramRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.SerializeToString,
            ),
            'GenerateAI': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAI,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerGenerateAIRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerGenerateAIResponse.SerializeToString,
            ),
            'GetTelegramTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelegramTargets,
                    request_deserializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramTargetsRequest.FromString,
                    response_serializer=dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramTargetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataforge.runtime.WorkerRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataforge.runtime.WorkerRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerRuntimeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/RegisterWorker',
            dataforge__protocol_dot_worker__runtime__pb2.RuntimeWorkerRegisterRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/HeartbeatWorker',
            dataforge__protocol_dot_worker__runtime__pb2.RuntimeWorkerHeartbeatRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/StopWorker',
            dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimBuildJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ClaimBuildJob',
            dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimBuildJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewBuildJobLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/RenewBuildJobLease',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildJobClaimRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewBuildJobLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimComputeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ClaimComputeRequest',
            dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimComputeRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewComputeRequestLeases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/RenewComputeRequestLeases',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewComputeRequestLeasesRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerRenewComputeRequestLeasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteComputeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/CompleteComputeRequest',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerCompleteComputeRequestRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailComputeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/FailComputeRequest',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerFailComputeRequestRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishDatasourceCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/PublishDatasourceCreate',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceCreateRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishDatasourceIngest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/PublishDatasourceIngest',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceIngestRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceIngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishDatasourceSchemaCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/PublishDatasourceSchemaCache',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceSchemaCacheRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPublishDatasourceSchemaCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDatasourceStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/RegisterDatasourceStage',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerRegisterDatasourceStageRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimStorageCleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ClaimStorageCleanup',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerClaimStorageCleanupRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerStorageCleanupClaimsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthorizeStorageCleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/AuthorizeStorageCleanup',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerStorageCleanupClaimRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteStorageCleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/CompleteStorageCleanup',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerCompleteStorageCleanupRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatasourceMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetDatasourceMetadata',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerDatasourceMetadataRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerDatasourceMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUdfCodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetUdfCodes',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerUdfCodesRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerUdfCodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComputeWorkerCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetComputeWorkerCredentials',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerCredentialsRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalysisMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetAnalysisMetadata',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerAnalysisMetadataRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerAnalysisMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuildCancelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetBuildCancelStatus',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildCancelStatusRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerBuildCancelStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBuildResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/UpdateBuildResult',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerUpdateBuildResultRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertOutputDatasource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/UpsertOutputDatasource',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerUpsertOutputDatasourceRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerUpsertOutputDatasourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHealthChecks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ListHealthChecks',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerListHealthChecksRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerListHealthChecksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordHealthCheckResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/RecordHealthCheckResults',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerRecordHealthCheckResultsRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateComputeWorkerRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/CreateComputeWorkerRun',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerCreateComputeWorkerRunRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComputeWorkerRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/UpdateComputeWorkerRun',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerUpdateComputeWorkerRunRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComputeWorkerRunState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetComputeWorkerRunState',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerRunStateRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerComputeWorkerRunStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailBuildJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/FailBuildJob',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerFailBuildJobRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeBuildJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/FinalizeBuildJob',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeBuildJobRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseBuildWorkerJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ReleaseBuildWorkerJobs',
            dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueuedBuildJobCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetQueuedBuildJobCount',
            dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileExpiredBuildJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ReconcileExpiredBuildJobs',
            dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileExpiredComputeRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ReconcileExpiredComputeRequests',
            dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdleBuildWorkerPids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetIdleBuildWorkerPids',
            dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerIdlePidsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPendingRuntimeWorkNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ListPendingRuntimeWorkNamespaces',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPendingRuntimeWorkNamespacesRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersistBuildEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/PersistBuildEvent',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistBuildEventRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistBuildEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBuildRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/StartBuildRun',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerStartBuildRunRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerStartBuildRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersistComputeWorkerSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/PersistComputeWorkerSnapshot',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPersistComputeWorkerSnapshotRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPendingDatasourceDeletes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/ListPendingDatasourceDeletes',
            dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerPendingDatasourceDeletesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeDatasourceDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/FinalizeDatasourceDelete',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeDatasourceDeleteRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerFinalizeDatasourceDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelegramSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetTelegramSettings',
            dataforge__protocol_dot_common__pb2.EmptyRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/SendEmail',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerSendEmailRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTelegram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/SendTelegram',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerSendTelegramRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GenerateAI',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerGenerateAIRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerGenerateAIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelegramTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.WorkerRuntimeService/GetTelegramTargets',
            dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramTargetsRequest.SerializeToString,
            dataforge__protocol_dot_worker__runtime__pb2.WorkerTelegramTargetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
