# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataforge_protocol/runtime_coordinator.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dataforge_protocol/runtime_coordinator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from dataforge_protocol import common_pb2 as dataforge__protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,dataforge_protocol/runtime_coordinator.proto\x12\x11\x64\x61taforge.runtime\x1a\x1b\x62uf/validate/validate.proto\x1a\x1f\x64\x61taforge_protocol/common.proto\"B\n#RuntimeCoordinatorGenerationRequest\x12\x1b\n\ngeneration\x18\x01 \x01(\x03\x42\x07\xbaH\x04\"\x02 \x00\"C\n$RuntimeCoordinatorGenerationResponse\x12\x1b\n\ngeneration\x18\x01 \x01(\x03\x42\x07\xbaH\x04\"\x02 \x00\x32\xa2\x02\n\x19RuntimeCoordinatorService\x12t\n\x18GetCoordinatorGeneration\x12\x1f.dataforge.runtime.EmptyRequest\x1a\x37.dataforge.runtime.RuntimeCoordinatorGenerationResponse\x12\x8e\x01\n\x1b\x41ssertCoordinatorGeneration\x12\x36.dataforge.runtime.RuntimeCoordinatorGenerationRequest\x1a\x37.dataforge.runtime.RuntimeCoordinatorGenerationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataforge_protocol.runtime_coordinator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNTIMECOORDINATORGENERATIONREQUEST'].fields_by_name['generation']._loaded_options = None
  _globals['_RUNTIMECOORDINATORGENERATIONREQUEST'].fields_by_name['generation']._serialized_options = b'\272H\004\"\002 \000'
  _globals['_RUNTIMECOORDINATORGENERATIONRESPONSE'].fields_by_name['generation']._loaded_options = None
  _globals['_RUNTIMECOORDINATORGENERATIONRESPONSE'].fields_by_name['generation']._serialized_options = b'\272H\004\"\002 \000'
  _globals['_RUNTIMECOORDINATORGENERATIONREQUEST']._serialized_start=129
  _globals['_RUNTIMECOORDINATORGENERATIONREQUEST']._serialized_end=195
  _globals['_RUNTIMECOORDINATORGENERATIONRESPONSE']._serialized_start=197
  _globals['_RUNTIMECOORDINATORGENERATIONRESPONSE']._serialized_end=264
  _globals['_RUNTIMECOORDINATORSERVICE']._serialized_start=267
  _globals['_RUNTIMECOORDINATORSERVICE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
