# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataforge_protocol/scheduler_runtime.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dataforge_protocol/scheduler_runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dataforge_protocol import common_pb2 as dataforge__protocol_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*dataforge_protocol/scheduler_runtime.proto\x12\x11\x64\x61taforge.runtime\x1a\x1f\x64\x61taforge_protocol/common.proto\"\x81\x01\n\x18SchedulerRegisterRequest\x12\x1b\n\tworker_id\x18\x01 \x01(\tR\x08workerId\x12\x1a\n\x08hostname\x18\x02 \x01(\tR\x08hostname\x12\x10\n\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1a\n\x08\x63\x61pacity\x18\x04 \x01(\x05R\x08\x63\x61pacity\"\x95\x01\n\x14SchedulerEnqueuedRun\x12\x1c\n\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n\x0bschedule_id\x18\x02 \x01(\tR\nscheduleId\x12#\n\rdatasource_id\x18\x03 \x01(\tR\x0c\x64\x61tasourceId\x12\x19\n\x08\x62uild_id\x18\x04 \x01(\tR\x07\x62uildId\"\x8f\x01\n\x13SchedulerRunFailure\x12\x1c\n\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n\x0bschedule_id\x18\x02 \x01(\tR\nscheduleId\x12#\n\rdatasource_id\x18\x03 \x01(\tR\x0c\x64\x61tasourceId\x12\x14\n\x05\x65rror\x18\x04 \x01(\tR\x05\x65rror\"\xbc\x01\n\x17SchedulerRunDueResponse\x12\x18\n\x07handled\x18\x01 \x01(\x08R\x07handled\x12\x43\n\x08\x65nqueued\x18\x02 \x03(\x0b\x32\'.dataforge.runtime.SchedulerEnqueuedRunR\x08\x65nqueued\x12\x42\n\x08\x66\x61ilures\x18\x03 \x03(\x0b\x32&.dataforge.runtime.SchedulerRunFailureR\x08\x66\x61ilures2\xba\x03\n\x17SchedulerRuntimeService\x12j\n\x11RegisterScheduler\x12+.dataforge.runtime.SchedulerRegisterRequest\x1a(.dataforge.runtime.RuntimeWorkerResponse\x12g\n\x12HeartbeatScheduler\x12\'.dataforge.runtime.RuntimeWorkerRequest\x1a(.dataforge.runtime.RuntimeWorkerResponse\x12\x62\n\rStopScheduler\x12\'.dataforge.runtime.RuntimeWorkerRequest\x1a(.dataforge.runtime.RuntimeWorkerResponse\x12\x66\n\x0fRunDueSchedules\x12\'.dataforge.runtime.RuntimeWorkerRequest\x1a*.dataforge.runtime.SchedulerRunDueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataforge_protocol.scheduler_runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULERREGISTERREQUEST']._serialized_start=99
  _globals['_SCHEDULERREGISTERREQUEST']._serialized_end=228
  _globals['_SCHEDULERENQUEUEDRUN']._serialized_start=231
  _globals['_SCHEDULERENQUEUEDRUN']._serialized_end=380
  _globals['_SCHEDULERRUNFAILURE']._serialized_start=383
  _globals['_SCHEDULERRUNFAILURE']._serialized_end=526
  _globals['_SCHEDULERRUNDUERESPONSE']._serialized_start=529
  _globals['_SCHEDULERRUNDUERESPONSE']._serialized_end=717
  _globals['_SCHEDULERRUNTIMESERVICE']._serialized_start=720
  _globals['_SCHEDULERRUNTIMESERVICE']._serialized_end=1162
# @@protoc_insertion_point(module_scope)
