# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from dataforge_protocol import common_pb2 as dataforge__protocol_dot_common__pb2
from dataforge_protocol import scheduler_runtime_pb2 as dataforge__protocol_dot_scheduler__runtime__pb2


class SchedulerRuntimeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterScheduler = channel.unary_unary(
                '/dataforge.runtime.SchedulerRuntimeService/RegisterScheduler',
                request_serializer=dataforge__protocol_dot_scheduler__runtime__pb2.SchedulerRegisterRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.HeartbeatScheduler = channel.unary_unary(
                '/dataforge.runtime.SchedulerRuntimeService/HeartbeatScheduler',
                request_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.StopScheduler = channel.unary_unary(
                '/dataforge.runtime.SchedulerRuntimeService/StopScheduler',
                request_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
                _registered_method=True)
        self.RunDueSchedules = channel.unary_unary(
                '/dataforge.runtime.SchedulerRuntimeService/RunDueSchedules',
                request_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
                response_deserializer=dataforge__protocol_dot_scheduler__runtime__pb2.SchedulerRunDueResponse.FromString,
                _registered_method=True)


class SchedulerRuntimeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterScheduler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatScheduler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScheduler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunDueSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterScheduler': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterScheduler,
                    request_deserializer=dataforge__protocol_dot_scheduler__runtime__pb2.SchedulerRegisterRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'HeartbeatScheduler': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatScheduler,
                    request_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'StopScheduler': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScheduler,
                    request_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.FromString,
                    response_serializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.SerializeToString,
            ),
            'RunDueSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDueSchedules,
                    request_deserializer=dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.FromString,
                    response_serializer=dataforge__protocol_dot_scheduler__runtime__pb2.SchedulerRunDueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataforge.runtime.SchedulerRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataforge.runtime.SchedulerRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerRuntimeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterScheduler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.SchedulerRuntimeService/RegisterScheduler',
            dataforge__protocol_dot_scheduler__runtime__pb2.SchedulerRegisterRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatScheduler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.SchedulerRuntimeService/HeartbeatScheduler',
            dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopScheduler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.SchedulerRuntimeService/StopScheduler',
            dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
            dataforge__protocol_dot_common__pb2.RuntimeWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunDueSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataforge.runtime.SchedulerRuntimeService/RunDueSchedules',
            dataforge__protocol_dot_common__pb2.RuntimeWorkerRequest.SerializeToString,
            dataforge__protocol_dot_scheduler__runtime__pb2.SchedulerRunDueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
